FROM ubuntu 
MAINTAINER jewelsytofficial@gmail
RUN apt-get update 

RUN apt-get upgrade
RUN apt-get APR
RUN apt-get APR-Util
RUN apt-get update apache2
RUN apt-get install apache2
RUN service apache2 start

RUN apt-get clean 
EXPOSE 80/tcp

